# Generated by Django 5.2.7 on 2025-10-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LISTA', 'Lista'), ('DESCUENTO', 'Descuento'), ('MAYOREO', 'Mayoreo'), ('MINIMO', 'Mínimo'), ('CREDITO', 'Crédito')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price_types',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='price_A',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price_B',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price_C',
        ),
        migrations.CreateModel(
            name='ArticlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='articles.article')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_prices', to='articles.pricetype')),
            ],
            options={
                'db_table': 'article_prices',
                'ordering': ['price_type__id'],
                'unique_together': {('article', 'price_type')},
            },
        ),
    ]
