# Generated by Django 5.2.7 on 2025-10-10 23:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('SELLER', 'Seller'), ('CUSTOMER', 'Customer')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING', 'Pendiente'), ('BANNED', 'Suspendido'), ('REJECTED', 'Rechazado')], max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
