# Generated by Django 5.2.6 on 2025-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_admin_user_remove_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('SELLER', 'Vendedor'), ('PURCHASING', 'Compras'), ('CLIENT', 'Cliente'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
