# Generated by Django 5.2.7 on 2025-10-11 02:05

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(default=users.models.get_expiration_time),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.user'),
        ),
        migrations.AlterModelTable(
            name='token',
            table='tokens',
        ),
    ]
