# Generated by Django 5.2.6 on 2025-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='purchasingstaff',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente'), ('staff', 'Staff')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('baneado', 'Baneado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='PurchasingStaff',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
