# Generated by Django 5.2.7 on 2025-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_token_expires_alter_token_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('SELLER', 'Seller'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING', 'Pendiente'), ('BANNED', 'Suspendido'), ('REJECTED', 'Rechazado')], default='PENDIG', max_length=10),
        ),
    ]
