# Generated by Django 5.2.7 on 2025-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING', 'Pendiente'), ('BANNED', 'Suspendido'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
    ]
