# Generated by Django 5.2.6 on 2025-10-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_rol_alter_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profile_info',
        ),
    ]
