# Generated by Django 5.2.7 on 2025-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Persona'), ('BUSINESS', 'Empresa')], default='PENDING', max_length=10),
        ),
    ]
