# Generated by Django 5.2.7 on 2025-10-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Persona'), ('BUSINESS', 'Empresa')], default='PERSON', max_length=10),
        ),
    ]
