# Generated by Django 5.2.7 on 2025-10-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SEND', 'Enviada'), ('AUTHORIZED', 'Autorizada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10),
        ),
    ]
