# Generated by Django 5.2.7 on 2025-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_orders', '0002_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
