# Generated by Django 5.2.7 on 2025-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_orders', '0003_quotecounter_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
