# Generated by Django 5.2.7 on 2025-10-28 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_orders', '0004_alter_quoteitem_quantity'),
        ('users', '0006_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='article',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.CreateModel(
            name='QuoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_status_changes', to='users.user')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='quotes_orders.quote')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes_orders.status')),
            ],
            options={
                'db_table': 'quote_status_history',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
