# Generated by Django 5.2.7 on 2025-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_orders', '0005_status_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotestatus',
            name='note',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
