# Generated by Django 5.2.7 on 2025-10-30 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_orders', '0006_alter_quotestatus_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
